# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.api.markers_api import MarkersApi


class TestMarkersApi(unittest.TestCase):
    """MarkersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarkersApi()

    def tearDown(self) -> None:
        pass

    def test_clear_marker_subject(self) -> None:
        """Test case for clear_marker_subject

        removes an existing marker subject association
        """
        pass

    def test_update_marker(self) -> None:
        """Test case for update_marker

        updates an existing file area marker to assign faces or other subjects
        """
        pass


if __name__ == '__main__':
    unittest.main()
