# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.models.entity_album import EntityAlbum

class TestEntityAlbum(unittest.TestCase):
    """EntityAlbum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityAlbum:
        """Test EntityAlbum
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityAlbum`
        """
        model = EntityAlbum()
        if include_optional:
            return EntityAlbum(
                caption = '',
                category = '',
                country = '',
                created_at = '',
                created_by = '',
                day = 56,
                deleted_at = '',
                description = '',
                favorite = True,
                filter = '',
                id = 56,
                location = '',
                month = 56,
                notes = '',
                order = '',
                parent_uid = '',
                path = '',
                private = True,
                published_at = '',
                slug = '',
                state = '',
                template = '',
                thumb = '',
                thumb_src = '',
                title = '',
                type = '',
                uid = '',
                updated_at = '',
                year = 56
            )
        else:
            return EntityAlbum(
        )
        """

    def testEntityAlbum(self):
        """Test EntityAlbum"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
