# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_users_uid_avatar_post(self) -> None:
        """Test case for api_v1_users_uid_avatar_post

        """
        pass

    def test_api_v1_users_uid_passcode_activate_post(self) -> None:
        """Test case for api_v1_users_uid_passcode_activate_post

        """
        pass

    def test_api_v1_users_uid_passcode_confirm_post(self) -> None:
        """Test case for api_v1_users_uid_passcode_confirm_post

        """
        pass

    def test_api_v1_users_uid_passcode_deactivate_post(self) -> None:
        """Test case for api_v1_users_uid_passcode_deactivate_post

        """
        pass

    def test_api_v1_users_uid_passcode_post(self) -> None:
        """Test case for api_v1_users_uid_passcode_post

        """
        pass

    def test_api_v1_users_uid_password_put(self) -> None:
        """Test case for api_v1_users_uid_password_put

        """
        pass

    def test_api_v1_users_uid_put(self) -> None:
        """Test case for api_v1_users_uid_put

        """
        pass

    def test_api_v1_users_uid_sessions_get(self) -> None:
        """Test case for api_v1_users_uid_sessions_get

        """
        pass

    def test_users_uid_upload_token_post(self) -> None:
        """Test case for users_uid_upload_token_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
