# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.models.config_client_counts import ConfigClientCounts

class TestConfigClientCounts(unittest.TestCase):
    """ConfigClientCounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigClientCounts:
        """Test ConfigClientCounts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigClientCounts`
        """
        model = ConfigClientCounts()
        if include_optional:
            return ConfigClientCounts(
                albums = 56,
                all = 56,
                archived = 56,
                cameras = 56,
                countries = 56,
                favorites = 56,
                files = 56,
                folders = 56,
                hidden = 56,
                label_max_photos = 56,
                labels = 56,
                lenses = 56,
                live = 56,
                moments = 56,
                months = 56,
                people = 56,
                photos = 56,
                places = 56,
                private = 56,
                private_albums = 56,
                private_folders = 56,
                private_moments = 56,
                private_months = 56,
                private_states = 56,
                review = 56,
                states = 56,
                stories = 56,
                videos = 56
            )
        else:
            return ConfigClientCounts(
        )
        """

    def testConfigClientCounts(self):
        """Test ConfigClientCounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
