# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.api.files_api import FilesApi


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FilesApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_markers_post(self) -> None:
        """Test case for api_v1_markers_post

        """
        pass

    def test_change_file_orientation(self) -> None:
        """Test case for change_file_orientation

        changes the orientation of a file
        """
        pass

    def test_delete_file(self) -> None:
        """Test case for delete_file

        removes a file from storage
        """
        pass

    def test_get_download(self) -> None:
        """Test case for get_download

        returns the raw file data
        """
        pass

    def test_get_file(self) -> None:
        """Test case for get_file

        returns file details as JSON
        """
        pass

    def test_get_photo_download(self) -> None:
        """Test case for get_photo_download

        returns the primary file matching that belongs to the photo
        """
        pass

    def test_get_thumb(self) -> None:
        """Test case for get_thumb

        returns a thumbnail image with the requested size
        """
        pass

    def test_get_video(self) -> None:
        """Test case for get_video

        returns a video, optionally limited to a byte range for streaming
        """
        pass

    def test_users_uid_upload_token_post(self) -> None:
        """Test case for users_uid_upload_token_post

        """
        pass

    def test_zip_create(self) -> None:
        """Test case for zip_create

        creates a zip file archive for download
        """
        pass

    def test_zip_download(self) -> None:
        """Test case for zip_download

        downloads a zip file archive
        """
        pass


if __name__ == '__main__':
    unittest.main()
