# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.api.services_api import ServicesApi


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesApi()

    def tearDown(self) -> None:
        pass

    def test_add_service(self) -> None:
        """Test case for add_service

        creates a new remote account configuration
        """
        pass

    def test_delete_service(self) -> None:
        """Test case for delete_service

        removes a remote account configuration
        """
        pass

    def test_get_service(self) -> None:
        """Test case for get_service

        returns an account as JSON
        """
        pass

    def test_get_service_folders(self) -> None:
        """Test case for get_service_folders

        returns folders that belong to an account as JSON
        """
        pass

    def test_search_services(self) -> None:
        """Test case for search_services

        finds account settings and returns them as JSON
        """
        pass

    def test_update_service(self) -> None:
        """Test case for update_service

        updates a remote account configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
