# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.api.links_api import LinksApi


class TestLinksApi(unittest.TestCase):
    """LinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinksApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_entity_uid_links_post(self) -> None:
        """Test case for api_v1_entity_uid_links_post

        """
        pass

    def test_create_album_link(self) -> None:
        """Test case for create_album_link

        adds a new album share link and return it as JSON
        """
        pass

    def test_delete_album_link(self) -> None:
        """Test case for delete_album_link

        deletes an album share link
        """
        pass

    def test_get_album_links(self) -> None:
        """Test case for get_album_links

        returns all share links for the given UID as JSON
        """
        pass

    def test_update_album_link(self) -> None:
        """Test case for update_album_link

        updates an album share link and return it as JSON
        """
        pass


if __name__ == '__main__':
    unittest.main()
