# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.api.server_api import ServerApi
from test import _get_api_client


class TestServerApi(unittest.TestCase):
    """ServerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServerApi(_get_api_client())

    def tearDown(self) -> None:
        pass

    def test_get_status(self) -> None:
        """Test case for get_status

        reports if the server is operational
        """
        ret = self.api.get_status()
        self.assertEqual(ret['status'], 'operational')
        ret = self.api.get_status_with_http_info()
        self.assertEqual(ret.data['status'], 'operational')

        with self.assertRaises(Exception):
            api = ServerApi(_get_api_client(host='https://does.not.exist/'))
            _ = api.get_status()
            _ = api.get_status_with_http_info()


if __name__ == '__main__':
    unittest.main()
