# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.api.subjects_api import SubjectsApi


class TestSubjectsApi(unittest.TestCase):
    """SubjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubjectsApi()

    def tearDown(self) -> None:
        pass

    def test_clear_marker_subject(self) -> None:
        """Test case for clear_marker_subject

        removes an existing marker subject association
        """
        pass

    def test_dislike_subject(self) -> None:
        """Test case for dislike_subject

        removes the favorite flag from a subject
        """
        pass

    def test_get_subject(self) -> None:
        """Test case for get_subject

        returns a subject as JSON
        """
        pass

    def test_like_subject(self) -> None:
        """Test case for like_subject

        flags a subject as favorite
        """
        pass

    def test_search_subjects(self) -> None:
        """Test case for search_subjects

        finds and returns subjects as JSON
        """
        pass

    def test_update_marker(self) -> None:
        """Test case for update_marker

        updates an existing file area marker to assign faces or other subjects
        """
        pass

    def test_update_subject(self) -> None:
        """Test case for update_subject

        updates subject properties
        """
        pass


if __name__ == '__main__':
    unittest.main()
