# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from photoprism_client.api.albums_api import AlbumsApi


class TestAlbumsApi(unittest.TestCase):
    """AlbumsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlbumsApi()

    def tearDown(self) -> None:
        pass

    def test_add_photos_to_album(self) -> None:
        """Test case for add_photos_to_album

        adds photos to an album
        """
        pass

    def test_album_cover(self) -> None:
        """Test case for album_cover

        returns an album cover image
        """
        pass

    def test_batch_albums_delete(self) -> None:
        """Test case for batch_albums_delete

        permanently removes multiple albums
        """
        pass

    def test_clone_albums(self) -> None:
        """Test case for clone_albums

        creates a new album containing pictures from other albums
        """
        pass

    def test_create_album(self) -> None:
        """Test case for create_album

        creates a new album
        """
        pass

    def test_create_album_link(self) -> None:
        """Test case for create_album_link

        adds a new album share link and return it as JSON
        """
        pass

    def test_delete_album(self) -> None:
        """Test case for delete_album

        deletes an existing album
        """
        pass

    def test_delete_album_link(self) -> None:
        """Test case for delete_album_link

        deletes an album share link
        """
        pass

    def test_dislike_album(self) -> None:
        """Test case for dislike_album

        removes the favorite flag from an album
        """
        pass

    def test_download_album(self) -> None:
        """Test case for download_album

        streams the album contents as zip archiv
        """
        pass

    def test_get_album(self) -> None:
        """Test case for get_album

        returns album details as JSON
        """
        pass

    def test_get_album_links(self) -> None:
        """Test case for get_album_links

        returns all share links for the given UID as JSON
        """
        pass

    def test_get_moments_time(self) -> None:
        """Test case for get_moments_time

        returns monthly albums as JSON
        """
        pass

    def test_like_album(self) -> None:
        """Test case for like_album

        sets the favorite flag for an album
        """
        pass

    def test_remove_photos_from_album(self) -> None:
        """Test case for remove_photos_from_album

        removes photos from an album
        """
        pass

    def test_search_albums(self) -> None:
        """Test case for search_albums

        finds albums and returns them as JSON
        """
        pass

    def test_update_album(self) -> None:
        """Test case for update_album

        updates album metadata like title and description
        """
        pass

    def test_update_album_link(self) -> None:
        """Test case for update_album_link

        updates an album share link and return it as JSON
        """
        pass


if __name__ == '__main__':
    unittest.main()
