# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CustomizeDownloadName(str, Enum):
    """
    CustomizeDownloadName
    """

    """
    allowed enum values
    """
    FILE = 'file'
    ORIGINAL = 'original'
    SHARE = 'share'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CustomizeDownloadName from a JSON string"""
        return cls(json.loads(json_str))


