# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from photoprism_client.models.entity_album import EntityAlbum
from photoprism_client.models.entity_camera import EntityCamera
from photoprism_client.models.entity_cell import EntityCell
from photoprism_client.models.entity_details import EntityDetails
from photoprism_client.models.entity_file import EntityFile
from photoprism_client.models.entity_lens import EntityLens
from photoprism_client.models.entity_place import EntityPlace
from photoprism_client.models.time_duration import TimeDuration
from typing import Optional, Set
from typing_extensions import Self

class EntityPhoto(BaseModel):
    """
    EntityPhoto
    """ # noqa: E501
    albums: Optional[List[EntityAlbum]] = Field(default=None, alias="Albums")
    altitude: Optional[StrictInt] = Field(default=None, alias="Altitude")
    camera: Optional[EntityCamera] = Field(default=None, alias="Camera")
    camera_id: Optional[StrictInt] = Field(default=None, alias="CameraID")
    camera_serial: Optional[StrictStr] = Field(default=None, alias="CameraSerial")
    camera_src: Optional[StrictStr] = Field(default=None, alias="CameraSrc")
    cell: Optional[EntityCell] = Field(default=None, alias="Cell")
    cell_accuracy: Optional[StrictInt] = Field(default=None, alias="CellAccuracy")
    cell_id: Optional[StrictStr] = Field(default=None, alias="CellID")
    color: Optional[StrictInt] = Field(default=None, alias="Color")
    country: Optional[StrictStr] = Field(default=None, alias="Country")
    created_by: Optional[StrictStr] = Field(default=None, alias="CreatedBy")
    day: Optional[StrictInt] = Field(default=None, alias="Day")
    description: Optional[StrictStr] = Field(default=None, alias="Description")
    description_src: Optional[StrictStr] = Field(default=None, alias="DescriptionSrc")
    details: Optional[EntityDetails] = Field(default=None, alias="Details")
    document_id: Optional[StrictStr] = Field(default=None, alias="DocumentID")
    duration: Optional[TimeDuration] = Field(default=None, alias="Duration")
    estimated_at: Optional[StrictStr] = Field(default=None, alias="EstimatedAt")
    exposure: Optional[StrictStr] = Field(default=None, alias="Exposure")
    f_number: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="FNumber")
    faces: Optional[StrictInt] = Field(default=None, alias="Faces")
    favorite: Optional[StrictBool] = Field(default=None, alias="Favorite")
    focal_length: Optional[StrictInt] = Field(default=None, alias="FocalLength")
    iso: Optional[StrictInt] = Field(default=None, alias="Iso")
    lat: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Lat")
    lens: Optional[EntityLens] = Field(default=None, alias="Lens")
    lens_id: Optional[StrictInt] = Field(default=None, alias="LensID")
    lng: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Lng")
    month: Optional[StrictInt] = Field(default=None, alias="Month")
    name: Optional[StrictStr] = Field(default=None, alias="Name")
    original_name: Optional[StrictStr] = Field(default=None, alias="OriginalName")
    panorama: Optional[StrictBool] = Field(default=None, alias="Panorama")
    path: Optional[StrictStr] = Field(default=None, alias="Path")
    place: Optional[EntityPlace] = Field(default=None, alias="Place")
    place_id: Optional[StrictStr] = Field(default=None, alias="PlaceID")
    place_src: Optional[StrictStr] = Field(default=None, alias="PlaceSrc")
    private: Optional[StrictBool] = Field(default=None, alias="Private")
    published_at: Optional[StrictStr] = Field(default=None, alias="PublishedAt")
    quality: Optional[StrictInt] = Field(default=None, alias="Quality")
    resolution: Optional[StrictInt] = Field(default=None, alias="Resolution")
    scan: Optional[StrictBool] = Field(default=None, alias="Scan")
    stack: Optional[StrictInt] = Field(default=None, alias="Stack")
    taken_at: Optional[StrictStr] = Field(default=None, alias="TakenAt")
    taken_at_local: Optional[StrictStr] = Field(default=None, alias="TakenAtLocal")
    taken_src: Optional[StrictStr] = Field(default=None, alias="TakenSrc")
    time_zone: Optional[StrictStr] = Field(default=None, alias="TimeZone")
    title: Optional[StrictStr] = Field(default=None, alias="Title")
    title_src: Optional[StrictStr] = Field(default=None, alias="TitleSrc")
    type: Optional[StrictStr] = Field(default=None, alias="Type")
    type_src: Optional[StrictStr] = Field(default=None, alias="TypeSrc")
    uid: Optional[StrictStr] = Field(default=None, alias="UID")
    year: Optional[StrictInt] = Field(default=None, alias="Year")
    checked_at: Optional[StrictStr] = Field(default=None, alias="checkedAt")
    created_at: Optional[StrictStr] = Field(default=None, alias="createdAt")
    deleted_at: Optional[StrictStr] = Field(default=None, alias="deletedAt")
    edited_at: Optional[StrictStr] = Field(default=None, alias="editedAt")
    files: Optional[List[EntityFile]] = None
    id: Optional[StrictInt] = None
    labels: Optional[List[EntityPhotoLabel]] = None
    updated_at: Optional[StrictStr] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["Albums", "Altitude", "Camera", "CameraID", "CameraSerial", "CameraSrc", "Cell", "CellAccuracy", "CellID", "Color", "Country", "CreatedBy", "Day", "Description", "DescriptionSrc", "Details", "DocumentID", "Duration", "EstimatedAt", "Exposure", "FNumber", "Faces", "Favorite", "FocalLength", "Iso", "Lat", "Lens", "LensID", "Lng", "Month", "Name", "OriginalName", "Panorama", "Path", "Place", "PlaceID", "PlaceSrc", "Private", "PublishedAt", "Quality", "Resolution", "Scan", "Stack", "TakenAt", "TakenAtLocal", "TakenSrc", "TimeZone", "Title", "TitleSrc", "Type", "TypeSrc", "UID", "Year", "checkedAt", "createdAt", "deletedAt", "editedAt", "files", "id", "labels", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityPhoto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in albums (list)
        _items = []
        if self.albums:
            for _item_albums in self.albums:
                if _item_albums:
                    _items.append(_item_albums.to_dict())
            _dict['Albums'] = _items
        # override the default output from pydantic by calling `to_dict()` of camera
        if self.camera:
            _dict['Camera'] = self.camera.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cell
        if self.cell:
            _dict['Cell'] = self.cell.to_dict()
        # override the default output from pydantic by calling `to_dict()` of details
        if self.details:
            _dict['Details'] = self.details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of lens
        if self.lens:
            _dict['Lens'] = self.lens.to_dict()
        # override the default output from pydantic by calling `to_dict()` of place
        if self.place:
            _dict['Place'] = self.place.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityPhoto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Albums": [EntityAlbum.from_dict(_item) for _item in obj["Albums"]] if obj.get("Albums") is not None else None,
            "Altitude": obj.get("Altitude"),
            "Camera": EntityCamera.from_dict(obj["Camera"]) if obj.get("Camera") is not None else None,
            "CameraID": obj.get("CameraID"),
            "CameraSerial": obj.get("CameraSerial"),
            "CameraSrc": obj.get("CameraSrc"),
            "Cell": EntityCell.from_dict(obj["Cell"]) if obj.get("Cell") is not None else None,
            "CellAccuracy": obj.get("CellAccuracy"),
            "CellID": obj.get("CellID"),
            "Color": obj.get("Color"),
            "Country": obj.get("Country"),
            "CreatedBy": obj.get("CreatedBy"),
            "Day": obj.get("Day"),
            "Description": obj.get("Description"),
            "DescriptionSrc": obj.get("DescriptionSrc"),
            "Details": EntityDetails.from_dict(obj["Details"]) if obj.get("Details") is not None else None,
            "DocumentID": obj.get("DocumentID"),
            "Duration": obj.get("Duration"),
            "EstimatedAt": obj.get("EstimatedAt"),
            "Exposure": obj.get("Exposure"),
            "FNumber": obj.get("FNumber"),
            "Faces": obj.get("Faces"),
            "Favorite": obj.get("Favorite"),
            "FocalLength": obj.get("FocalLength"),
            "Iso": obj.get("Iso"),
            "Lat": obj.get("Lat"),
            "Lens": EntityLens.from_dict(obj["Lens"]) if obj.get("Lens") is not None else None,
            "LensID": obj.get("LensID"),
            "Lng": obj.get("Lng"),
            "Month": obj.get("Month"),
            "Name": obj.get("Name"),
            "OriginalName": obj.get("OriginalName"),
            "Panorama": obj.get("Panorama"),
            "Path": obj.get("Path"),
            "Place": EntityPlace.from_dict(obj["Place"]) if obj.get("Place") is not None else None,
            "PlaceID": obj.get("PlaceID"),
            "PlaceSrc": obj.get("PlaceSrc"),
            "Private": obj.get("Private"),
            "PublishedAt": obj.get("PublishedAt"),
            "Quality": obj.get("Quality"),
            "Resolution": obj.get("Resolution"),
            "Scan": obj.get("Scan"),
            "Stack": obj.get("Stack"),
            "TakenAt": obj.get("TakenAt"),
            "TakenAtLocal": obj.get("TakenAtLocal"),
            "TakenSrc": obj.get("TakenSrc"),
            "TimeZone": obj.get("TimeZone"),
            "Title": obj.get("Title"),
            "TitleSrc": obj.get("TitleSrc"),
            "Type": obj.get("Type"),
            "TypeSrc": obj.get("TypeSrc"),
            "UID": obj.get("UID"),
            "Year": obj.get("Year"),
            "checkedAt": obj.get("checkedAt"),
            "createdAt": obj.get("createdAt"),
            "deletedAt": obj.get("deletedAt"),
            "editedAt": obj.get("editedAt"),
            "files": [EntityFile.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None,
            "id": obj.get("id"),
            "labels": [EntityPhotoLabel.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "updatedAt": obj.get("updatedAt")
        })
        return _obj

from photoprism_client.models.entity_photo_label import EntityPhotoLabel
# TODO: Rewrite to not use raise_errors
EntityPhoto.model_rebuild(raise_errors=False)

