# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TimeDuration(int, Enum):
    """
    TimeDuration
    """

    """
    allowed enum values
    """
    minDuration = -9223372036854775808
    maxDuration = 9223372036854775807
    Nanosecond = 1
    Microsecond = 1000
    Millisecond = 1000000
    Second = 1000000000
    Minute = 60000000000
    Hour = 3600000000000

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TimeDuration from a JSON string"""
        return cls(json.loads(json_str))


